title: "Brian Sipula"
name: &name "Brian Sipula"
description: "Researcher in Blockchain-Based E-Voting Systems | DBA | Lusaka, Zambia"
url: "https://briansipula.github.io"
repository: "briansipula/briansipula.github.io"
